In [ ]:
import pandas as pd
import numpy as np

In [ ]:
fake=pd.read_csv('/content/Fake.csv.zip')

In [ ]:
true=pd.read_csv('/content/True.csv.zip')

In [ ]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"


In [ ]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"


In [ ]:
true['label']=1

In [ ]:
fake['label']=0;

In [ ]:
news=pd.concat([fake,true],axis=0)

In [ ]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1


In [ ]:
news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1


In [ ]:
news.isnull().sum()

,0
text,0
label,0


In [ ]:
columns_to_drop = ['title', 'subject', 'date']
existing_columns = [col for col in columns_to_drop if col in news.columns]
if existing_columns:
    news = news.drop(existing_columns, axis=1)

In [ ]:
news

,text,label
0,Donald Trump just couldn t wish all Americans ...,0
1,House Intelligence Committee Chairman Devin Nu...,0
2,"On Friday, it was revealed that former Milwauk...",0
3,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis used his annual Christmas Day mes...,0
...,...,...
21412,BRUSSELS (Reuters) - NATO allies on Tuesday we...,1
21413,"LONDON (Reuters) - LexisNexis, a provider of l...",1
21414,MINSK (Reuters) - In the shadow of disused Sov...,1
21415,MOSCOW (Reuters) - Vatican Secretary of State ...,1


In [ ]:
# news=news.drop(['index'],axis=1,inplace=True) # This line caused a KeyError because the 'index' column does not exist.

In [ ]:
news

,text,label
0,Donald Trump just couldn t wish all Americans ...,0
1,House Intelligence Committee Chairman Devin Nu...,0
2,"On Friday, it was revealed that former Milwauk...",0
3,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis used his annual Christmas Day mes...,0
...,...,...
21412,BRUSSELS (Reuters) - NATO allies on Tuesday we...,1
21413,"LONDON (Reuters) - LexisNexis, a provider of l...",1
21414,MINSK (Reuters) - In the shadow of disused Sov...,1
21415,MOSCOW (Reuters) - Vatican Secretary of State ...,1


In [ ]:
news = news.sample(frac=1).reset_index(drop=True)

In [ ]:
news

,text,label
0,One of the most beloved public figures in the ...,0
1,"During his campaign, Donald Trump routinely ca...",0
2,PARIS (Reuters) - President Emmanuel Macron ha...,1
3,Despite what many racists say and regardless o...,0
4,If this had been a Tea Party group attacking N...,0
...,...,...
44893,President Trump spoke at the State Banquet dur...,0
44894,"SOCHI, Russia (Reuters) - Kremlin spokesman Dm...",1
44895,WASHINGTON (Reuters) - The U.S. Congress shoul...,1
44896,The Democrats will stop at nothing to win this...,0


In [ ]:
news.head()

,text,label
0,One of the most beloved public figures in the ...,0
1,"During his campaign, Donald Trump routinely ca...",0
2,PARIS (Reuters) - President Emmanuel Macron ha...,1
3,Despite what many racists say and regardless o...,0
4,If this had been a Tea Party group attacking N...,0


In [ ]:
import re

In [ ]:
def wordopt(text):
  text = text.lower()
  # Remove URLs
  text = re.sub(r'https?://\S+|www\.\S+', '', text)
  # Remove HTML tags
  text = re.sub(r'<.*?>', '', text)
  # Remove digits
  text = re.sub(r'\d', '', text)
  # Remove punctuation and special characters, but keep spaces
  text = re.sub(r'[^a-zA-Z\s]', ' ', text)
  # Remove newlines
  text = re.sub(r'\n', ' ', text)
  # Remove extra spaces
  text = re.sub(r'\s+', ' ', text).strip()
  return text

In [ ]:
news['text']=news['text'].apply(wordopt)

In [ ]:
news['text']=news['text'].apply(wordopt)

In [ ]:
news['text']

,text
0,one of the most beloved public figures in the ...
1,during his campaign donald trump routinely cal...
2,paris reuters president emmanuel macron has sa...
3,despite what many racists say and regardless o...
4,if this had been a tea party group attacking n...
...,...
44893,president trump spoke at the state banquet dur...
44894,sochi russia reuters kremlin spokesman dmitry ...
44895,washington reuters the u s congress should giv...
44896,the democrats will stop at nothing to win this...


In [ ]:
x=news['text']
y=news['label']
x

,text
0,one of the most beloved public figures in the ...
1,during his campaign donald trump routinely cal...
2,paris reuters president emmanuel macron has sa...
3,despite what many racists say and regardless o...
4,if this had been a tea party group attacking n...
...,...
44893,president trump spoke at the state banquet dur...
44894,sochi russia reuters kremlin spokesman dmitry ...
44895,washington reuters the u s congress should giv...
44896,the democrats will stop at nothing to win this...


In [ ]:
y

,label
0,0
1,0
2,1
3,0
4,0
...,...
44893,0
44894,1
44895,1
44896,0


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
x_train.shape

(31428,)

In [ ]:
y_train.shape

(31428,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

In [ ]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6431147 stored elements and shape (31428, 96636)>

In [ ]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2768645 stored elements and shape (13470, 96636)>

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
reg=LogisticRegression()
reg.fit(xv_train,y_train)

LogisticRegression()

In [ ]:
predict=reg.predict(xv_test)

In [ ]:
predict

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
reg.score(xv_test,y_test)

0.9866369710467706

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7070
           1       0.98      0.99      0.99      6400

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(xv_train,y_train)

DecisionTreeClassifier()

In [ ]:
pred_dct=dt.predict(xv_test)
pred_dct

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
dt.score(xv_test,y_test)

0.9953229398663697

In [ ]:
print(classification_report(y_test,pred_dct))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7070
           1       0.99      1.00      1.00      6400

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xv_train,y_train)

RandomForestClassifier()

In [ ]:
pred_rfc=rfc.predict(xv_test)
pred_rfc

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
rfc.score(xv_test,y_test)

0.9887899034892353

In [ ]:
print(classification_report(y_test,pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7070
           1       0.99      0.99      0.99      6400

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470



In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(xv_train,y_train)

GradientBoostingClassifier()

In [ ]:
pred_gbc=gbc.predict(xv_test)
pred_gbc

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
gbc.score(xv_test,y_test)

0.9953971789161099

In [ ]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7070
           1       0.99      1.00      1.00      6400

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [ ]:
def ouput_label(n):
  if n==0:
    return "It is a fake news"
  elif n==1:
    return "It is a genuine news"

In [ ]:
def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  predict=reg.predict(new_xv_test)
  pred_rfc=rfc.predict(new_xv_test)
  pred_dct=dt.predict(new_xv_test)
  pred_gbc=gbc.predict(new_xv_test)
  print("\n\nLogistic Regression Prediction: {} ".format(ouput_label(predict[0])))
  print("\n\nRandom Forest Prediction:{}".format(ouput_label(pred_rfc[0])))
  print("\n\nDecision Tree Prediction:{}".format(output_label(pred_dct[0])))
  print("\n\nGradient Boosting Prediction:{}".format(output_label(pred_gbc[0])))